// Mocks generated by Mockito 5.4.6 from annotations
// in haveno2dart/test/haveno_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:grpc/service_api.dart' as _i2;
import 'package:grpc/src/client/call.dart' as _i3;
import 'package:haveno2dart/src/generated/grpc.pb.dart' as _i5;
import 'package:haveno2dart/src/generated/grpc.pbgrpc.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponseFuture_0<R> extends _i1.SmartFake
    implements _i2.ResponseFuture<R> {
  _FakeResponseFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientCall_1<Q1, R1> extends _i1.SmartFake
    implements _i3.ClientCall<Q1, R1> {
  _FakeClientCall_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponseStream_2<R1> extends _i1.SmartFake
    implements _i2.ResponseStream<R1> {
  _FakeResponseStream_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetVersionClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVersionClient extends _i1.Mock implements _i4.GetVersionClient {
  @override
  _i2.ResponseFuture<_i5.GetVersionReply> getVersion(
    _i5.GetVersionRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVersion, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetVersionReply>(
              this,
              Invocation.method(#getVersion, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetVersionReply>(
                  this,
                  Invocation.method(
                    #getVersion,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetVersionReply>);

  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i3.ClientCall<Q, R>);

  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createUnaryCall,
              [method, request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseFuture_0<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseFuture<R>);

  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createStreamingCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeResponseStream_2<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseStream_2<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseStream<R>);
}

/// A class which mocks [WalletsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletsClient extends _i1.Mock implements _i4.WalletsClient {
  @override
  _i2.ResponseFuture<_i5.GetBalancesReply> getBalances(
    _i5.GetBalancesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBalances, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetBalancesReply>(
              this,
              Invocation.method(#getBalances, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetBalancesReply>(
                  this,
                  Invocation.method(
                    #getBalances,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetBalancesReply>);

  @override
  _i2.ResponseFuture<_i5.GetXmrSeedReply> getXmrSeed(
    _i5.GetXmrSeedRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getXmrSeed, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetXmrSeedReply>(
              this,
              Invocation.method(#getXmrSeed, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetXmrSeedReply>(
                  this,
                  Invocation.method(
                    #getXmrSeed,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetXmrSeedReply>);

  @override
  _i2.ResponseFuture<_i5.GetXmrPrimaryAddressReply> getXmrPrimaryAddress(
    _i5.GetXmrPrimaryAddressRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getXmrPrimaryAddress,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.GetXmrPrimaryAddressReply>(
              this,
              Invocation.method(
                #getXmrPrimaryAddress,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetXmrPrimaryAddressReply>(
                  this,
                  Invocation.method(
                    #getXmrPrimaryAddress,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetXmrPrimaryAddressReply>);

  @override
  _i2.ResponseFuture<_i5.GetXmrNewSubaddressReply> getXmrNewSubaddress(
    _i5.GetXmrNewSubaddressRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getXmrNewSubaddress,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.GetXmrNewSubaddressReply>(
              this,
              Invocation.method(
                #getXmrNewSubaddress,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetXmrNewSubaddressReply>(
                  this,
                  Invocation.method(
                    #getXmrNewSubaddress,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetXmrNewSubaddressReply>);

  @override
  _i2.ResponseFuture<_i5.GetXmrTxsReply> getXmrTxs(
    _i5.GetXmrTxsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getXmrTxs, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetXmrTxsReply>(
              this,
              Invocation.method(#getXmrTxs, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetXmrTxsReply>(
                  this,
                  Invocation.method(#getXmrTxs, [request], {#options: options}),
                ),
          )
          as _i2.ResponseFuture<_i5.GetXmrTxsReply>);

  @override
  _i2.ResponseFuture<_i5.CreateXmrTxReply> createXmrTx(
    _i5.CreateXmrTxRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createXmrTx, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.CreateXmrTxReply>(
              this,
              Invocation.method(#createXmrTx, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.CreateXmrTxReply>(
                  this,
                  Invocation.method(
                    #createXmrTx,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.CreateXmrTxReply>);

  @override
  _i2.ResponseFuture<_i5.CreateXmrSweepTxsReply> createXmrSweepTxs(
    _i5.CreateXmrSweepTxsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createXmrSweepTxs,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.CreateXmrSweepTxsReply>(
              this,
              Invocation.method(
                #createXmrSweepTxs,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.CreateXmrSweepTxsReply>(
                  this,
                  Invocation.method(
                    #createXmrSweepTxs,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.CreateXmrSweepTxsReply>);

  @override
  _i2.ResponseFuture<_i5.RelayXmrTxsReply> relayXmrTxs(
    _i5.RelayXmrTxsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#relayXmrTxs, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.RelayXmrTxsReply>(
              this,
              Invocation.method(#relayXmrTxs, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.RelayXmrTxsReply>(
                  this,
                  Invocation.method(
                    #relayXmrTxs,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.RelayXmrTxsReply>);

  @override
  _i2.ResponseFuture<_i5.GetAddressBalanceReply> getAddressBalance(
    _i5.GetAddressBalanceRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAddressBalance,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.GetAddressBalanceReply>(
              this,
              Invocation.method(
                #getAddressBalance,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetAddressBalanceReply>(
                  this,
                  Invocation.method(
                    #getAddressBalance,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetAddressBalanceReply>);

  @override
  _i2.ResponseFuture<_i5.GetFundingAddressesReply> getFundingAddresses(
    _i5.GetFundingAddressesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFundingAddresses,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.GetFundingAddressesReply>(
              this,
              Invocation.method(
                #getFundingAddresses,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetFundingAddressesReply>(
                  this,
                  Invocation.method(
                    #getFundingAddresses,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetFundingAddressesReply>);

  @override
  _i2.ResponseFuture<_i5.SetWalletPasswordReply> setWalletPassword(
    _i5.SetWalletPasswordRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setWalletPassword,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.SetWalletPasswordReply>(
              this,
              Invocation.method(
                #setWalletPassword,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.SetWalletPasswordReply>(
                  this,
                  Invocation.method(
                    #setWalletPassword,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.SetWalletPasswordReply>);

  @override
  _i2.ResponseFuture<_i5.RemoveWalletPasswordReply> removeWalletPassword(
    _i5.RemoveWalletPasswordRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #removeWalletPassword,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.RemoveWalletPasswordReply>(
              this,
              Invocation.method(
                #removeWalletPassword,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.RemoveWalletPasswordReply>(
                  this,
                  Invocation.method(
                    #removeWalletPassword,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.RemoveWalletPasswordReply>);

  @override
  _i2.ResponseFuture<_i5.LockWalletReply> lockWallet(
    _i5.LockWalletRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#lockWallet, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.LockWalletReply>(
              this,
              Invocation.method(#lockWallet, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.LockWalletReply>(
                  this,
                  Invocation.method(
                    #lockWallet,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.LockWalletReply>);

  @override
  _i2.ResponseFuture<_i5.UnlockWalletReply> unlockWallet(
    _i5.UnlockWalletRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unlockWallet, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.UnlockWalletReply>(
              this,
              Invocation.method(#unlockWallet, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.UnlockWalletReply>(
                  this,
                  Invocation.method(
                    #unlockWallet,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.UnlockWalletReply>);

  @override
  _i2.ResponseFuture<_i5.GetWalletHeightReply> getHeight(
    _i5.GetWalletHeightRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHeight, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetWalletHeightReply>(
              this,
              Invocation.method(#getHeight, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetWalletHeightReply>(
                  this,
                  Invocation.method(#getHeight, [request], {#options: options}),
                ),
          )
          as _i2.ResponseFuture<_i5.GetWalletHeightReply>);

  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i3.ClientCall<Q, R>);

  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createUnaryCall,
              [method, request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseFuture_0<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseFuture<R>);

  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createStreamingCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeResponseStream_2<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseStream_2<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseStream<R>);
}

/// A class which mocks [PaymentAccountsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentAccountsClient extends _i1.Mock
    implements _i4.PaymentAccountsClient {
  @override
  _i2.ResponseFuture<_i5.CreatePaymentAccountReply> createPaymentAccount(
    _i5.CreatePaymentAccountRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createPaymentAccount,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.CreatePaymentAccountReply>(
              this,
              Invocation.method(
                #createPaymentAccount,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.CreatePaymentAccountReply>(
                  this,
                  Invocation.method(
                    #createPaymentAccount,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.CreatePaymentAccountReply>);

  @override
  _i2.ResponseFuture<_i5.GetPaymentAccountsReply> getPaymentAccounts(
    _i5.GetPaymentAccountsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPaymentAccounts,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.GetPaymentAccountsReply>(
              this,
              Invocation.method(
                #getPaymentAccounts,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetPaymentAccountsReply>(
                  this,
                  Invocation.method(
                    #getPaymentAccounts,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetPaymentAccountsReply>);

  @override
  _i2.ResponseFuture<_i5.GetPaymentMethodsReply> getPaymentMethods(
    _i5.GetPaymentMethodsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPaymentMethods,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.GetPaymentMethodsReply>(
              this,
              Invocation.method(
                #getPaymentMethods,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetPaymentMethodsReply>(
                  this,
                  Invocation.method(
                    #getPaymentMethods,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetPaymentMethodsReply>);

  @override
  _i2.ResponseFuture<_i5.GetPaymentAccountFormReply> getPaymentAccountForm(
    _i5.GetPaymentAccountFormRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPaymentAccountForm,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.GetPaymentAccountFormReply>(
              this,
              Invocation.method(
                #getPaymentAccountForm,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetPaymentAccountFormReply>(
                  this,
                  Invocation.method(
                    #getPaymentAccountForm,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetPaymentAccountFormReply>);

  @override
  _i2.ResponseFuture<_i5.GetPaymentAccountFormAsJsonReply>
  getPaymentAccountFormAsJson(
    _i5.GetPaymentAccountFormAsJsonRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPaymentAccountFormAsJson,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_0<_i5.GetPaymentAccountFormAsJsonReply>(
                  this,
                  Invocation.method(
                    #getPaymentAccountFormAsJson,
                    [request],
                    {#options: options},
                  ),
                ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetPaymentAccountFormAsJsonReply>(
                  this,
                  Invocation.method(
                    #getPaymentAccountFormAsJson,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetPaymentAccountFormAsJsonReply>);

  @override
  _i2.ResponseFuture<_i5.CreateCryptoCurrencyPaymentAccountReply>
  createCryptoCurrencyPaymentAccount(
    _i5.CreateCryptoCurrencyPaymentAccountRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createCryptoCurrencyPaymentAccount,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_0<
                  _i5.CreateCryptoCurrencyPaymentAccountReply
                >(
                  this,
                  Invocation.method(
                    #createCryptoCurrencyPaymentAccount,
                    [request],
                    {#options: options},
                  ),
                ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<
                  _i5.CreateCryptoCurrencyPaymentAccountReply
                >(
                  this,
                  Invocation.method(
                    #createCryptoCurrencyPaymentAccount,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.CreateCryptoCurrencyPaymentAccountReply>);

  @override
  _i2.ResponseFuture<_i5.DeletePaymentAccountReply> deletePaymentAccount(
    _i5.DeletePaymentAccountRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deletePaymentAccount,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.DeletePaymentAccountReply>(
              this,
              Invocation.method(
                #deletePaymentAccount,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.DeletePaymentAccountReply>(
                  this,
                  Invocation.method(
                    #deletePaymentAccount,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.DeletePaymentAccountReply>);

  @override
  _i2.ResponseFuture<_i5.GetCryptoCurrencyPaymentMethodsReply>
  getCryptoCurrencyPaymentMethods(
    _i5.GetCryptoCurrencyPaymentMethodsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCryptoCurrencyPaymentMethods,
              [request],
              {#options: options},
            ),
            returnValue:
                _FakeResponseFuture_0<_i5.GetCryptoCurrencyPaymentMethodsReply>(
                  this,
                  Invocation.method(
                    #getCryptoCurrencyPaymentMethods,
                    [request],
                    {#options: options},
                  ),
                ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetCryptoCurrencyPaymentMethodsReply>(
                  this,
                  Invocation.method(
                    #getCryptoCurrencyPaymentMethods,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetCryptoCurrencyPaymentMethodsReply>);

  @override
  _i2.ResponseFuture<_i5.ValidateFormFieldReply> validateFormField(
    _i5.ValidateFormFieldRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateFormField,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.ValidateFormFieldReply>(
              this,
              Invocation.method(
                #validateFormField,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.ValidateFormFieldReply>(
                  this,
                  Invocation.method(
                    #validateFormField,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.ValidateFormFieldReply>);

  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i3.ClientCall<Q, R>);

  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createUnaryCall,
              [method, request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseFuture_0<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseFuture<R>);

  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createStreamingCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeResponseStream_2<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseStream_2<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseStream<R>);
}

/// A class which mocks [OffersClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffersClient extends _i1.Mock implements _i4.OffersClient {
  @override
  _i2.ResponseFuture<_i5.GetOfferReply> getOffer(
    _i5.GetOfferRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOffer, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetOfferReply>(
              this,
              Invocation.method(#getOffer, [request], {#options: options}),
            ),
            returnValueForMissingStub: _FakeResponseFuture_0<_i5.GetOfferReply>(
              this,
              Invocation.method(#getOffer, [request], {#options: options}),
            ),
          )
          as _i2.ResponseFuture<_i5.GetOfferReply>);

  @override
  _i2.ResponseFuture<_i5.GetMyOfferReply> getMyOffer(
    _i5.GetMyOfferRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOffer, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetMyOfferReply>(
              this,
              Invocation.method(#getMyOffer, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetMyOfferReply>(
                  this,
                  Invocation.method(
                    #getMyOffer,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetMyOfferReply>);

  @override
  _i2.ResponseFuture<_i5.GetOffersReply> getOffers(
    _i5.GetOffersRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOffers, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetOffersReply>(
              this,
              Invocation.method(#getOffers, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetOffersReply>(
                  this,
                  Invocation.method(#getOffers, [request], {#options: options}),
                ),
          )
          as _i2.ResponseFuture<_i5.GetOffersReply>);

  @override
  _i2.ResponseFuture<_i5.GetMyOffersReply> getMyOffers(
    _i5.GetMyOffersRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMyOffers, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetMyOffersReply>(
              this,
              Invocation.method(#getMyOffers, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetMyOffersReply>(
                  this,
                  Invocation.method(
                    #getMyOffers,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetMyOffersReply>);

  @override
  _i2.ResponseFuture<_i5.PostOfferReply> postOffer(
    _i5.PostOfferRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postOffer, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.PostOfferReply>(
              this,
              Invocation.method(#postOffer, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.PostOfferReply>(
                  this,
                  Invocation.method(#postOffer, [request], {#options: options}),
                ),
          )
          as _i2.ResponseFuture<_i5.PostOfferReply>);

  @override
  _i2.ResponseFuture<_i5.EditOfferReply> editOffer(
    _i5.EditOfferRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editOffer, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.EditOfferReply>(
              this,
              Invocation.method(#editOffer, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.EditOfferReply>(
                  this,
                  Invocation.method(#editOffer, [request], {#options: options}),
                ),
          )
          as _i2.ResponseFuture<_i5.EditOfferReply>);

  @override
  _i2.ResponseFuture<_i5.DeactivateOfferReply> deactivateOffer(
    _i5.DeactivateOfferRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deactivateOffer, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.DeactivateOfferReply>(
              this,
              Invocation.method(
                #deactivateOffer,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.DeactivateOfferReply>(
                  this,
                  Invocation.method(
                    #deactivateOffer,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.DeactivateOfferReply>);

  @override
  _i2.ResponseFuture<_i5.ActivateOfferReply> activateOffer(
    _i5.ActivateOfferRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#activateOffer, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.ActivateOfferReply>(
              this,
              Invocation.method(#activateOffer, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.ActivateOfferReply>(
                  this,
                  Invocation.method(
                    #activateOffer,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.ActivateOfferReply>);

  @override
  _i2.ResponseFuture<_i5.CancelOfferReply> cancelOffer(
    _i5.CancelOfferRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOffer, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.CancelOfferReply>(
              this,
              Invocation.method(#cancelOffer, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.CancelOfferReply>(
                  this,
                  Invocation.method(
                    #cancelOffer,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.CancelOfferReply>);

  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i3.ClientCall<Q, R>);

  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createUnaryCall,
              [method, request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseFuture_0<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseFuture<R>);

  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createStreamingCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeResponseStream_2<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseStream_2<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseStream<R>);
}

/// A class which mocks [TradesClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTradesClient extends _i1.Mock implements _i4.TradesClient {
  @override
  _i2.ResponseFuture<_i5.GetTradeReply> getTrade(
    _i5.GetTradeRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrade, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetTradeReply>(
              this,
              Invocation.method(#getTrade, [request], {#options: options}),
            ),
            returnValueForMissingStub: _FakeResponseFuture_0<_i5.GetTradeReply>(
              this,
              Invocation.method(#getTrade, [request], {#options: options}),
            ),
          )
          as _i2.ResponseFuture<_i5.GetTradeReply>);

  @override
  _i2.ResponseFuture<_i5.GetTradesReply> getTrades(
    _i5.GetTradesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrades, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetTradesReply>(
              this,
              Invocation.method(#getTrades, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetTradesReply>(
                  this,
                  Invocation.method(#getTrades, [request], {#options: options}),
                ),
          )
          as _i2.ResponseFuture<_i5.GetTradesReply>);

  @override
  _i2.ResponseFuture<_i5.TakeOfferReply> takeOffer(
    _i5.TakeOfferRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#takeOffer, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.TakeOfferReply>(
              this,
              Invocation.method(#takeOffer, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.TakeOfferReply>(
                  this,
                  Invocation.method(#takeOffer, [request], {#options: options}),
                ),
          )
          as _i2.ResponseFuture<_i5.TakeOfferReply>);

  @override
  _i2.ResponseFuture<_i5.ConfirmPaymentSentReply> confirmPaymentSent(
    _i5.ConfirmPaymentSentRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmPaymentSent,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.ConfirmPaymentSentReply>(
              this,
              Invocation.method(
                #confirmPaymentSent,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.ConfirmPaymentSentReply>(
                  this,
                  Invocation.method(
                    #confirmPaymentSent,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.ConfirmPaymentSentReply>);

  @override
  _i2.ResponseFuture<_i5.ConfirmPaymentReceivedReply> confirmPaymentReceived(
    _i5.ConfirmPaymentReceivedRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmPaymentReceived,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<_i5.ConfirmPaymentReceivedReply>(
              this,
              Invocation.method(
                #confirmPaymentReceived,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.ConfirmPaymentReceivedReply>(
                  this,
                  Invocation.method(
                    #confirmPaymentReceived,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.ConfirmPaymentReceivedReply>);

  @override
  _i2.ResponseFuture<_i5.CompleteTradeReply> completeTrade(
    _i5.CompleteTradeRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeTrade, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.CompleteTradeReply>(
              this,
              Invocation.method(#completeTrade, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.CompleteTradeReply>(
                  this,
                  Invocation.method(
                    #completeTrade,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.CompleteTradeReply>);

  @override
  _i2.ResponseFuture<_i5.WithdrawFundsReply> withdrawFunds(
    _i5.WithdrawFundsRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#withdrawFunds, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.WithdrawFundsReply>(
              this,
              Invocation.method(#withdrawFunds, [request], {#options: options}),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.WithdrawFundsReply>(
                  this,
                  Invocation.method(
                    #withdrawFunds,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.WithdrawFundsReply>);

  @override
  _i2.ResponseFuture<_i5.GetChatMessagesReply> getChatMessages(
    _i5.GetChatMessagesRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatMessages, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.GetChatMessagesReply>(
              this,
              Invocation.method(
                #getChatMessages,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.GetChatMessagesReply>(
                  this,
                  Invocation.method(
                    #getChatMessages,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.GetChatMessagesReply>);

  @override
  _i2.ResponseFuture<_i5.SendChatMessageReply> sendChatMessage(
    _i5.SendChatMessageRequest? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendChatMessage, [request], {#options: options}),
            returnValue: _FakeResponseFuture_0<_i5.SendChatMessageReply>(
              this,
              Invocation.method(
                #sendChatMessage,
                [request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub:
                _FakeResponseFuture_0<_i5.SendChatMessageReply>(
                  this,
                  Invocation.method(
                    #sendChatMessage,
                    [request],
                    {#options: options},
                  ),
                ),
          )
          as _i2.ResponseFuture<_i5.SendChatMessageReply>);

  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i3.ClientCall<Q, R>);

  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createUnaryCall,
              [method, request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_0<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseFuture_0<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseFuture<R>);

  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i6.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createStreamingCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeResponseStream_2<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeResponseStream_2<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseStream<R>);
}
